### ISSUE TITLE
RPi4 HA Docker - MQTT No sensor

### ISSUE THREAD

**Issue by EvoSems** [meltaxa/solariot#102]
Hi guys. great project, this is the only option I could find that will work with my SG5KD, as there is no useable lan port (is there one inside the unit??) I have the smart meter connected to my other port which reads my grid data (SG Smart Meter_002_001)

I'm not very code friendly. but I have managed to create my docker file and integrate to HA Core on my Rpi4. with my following command.

sudo docker run -d --name soloriot --restart=unless-stopped -v /home/xxx/solariot:/config --network=host meltaxa/solariot:latest

occasionally I do get some weird connect errors. but it works mostly 1/5 times issue the command above.
`INFO:root:Loaded config sungrow-sg5kd
INFO:root:Creating SungrowModbusTcpClient
INFO:root:Connecting
INFO:root:Connected
INFO:root:Configured MQTT Client
INFO:root:No Prometheus configuration detected
INFO:root:No InfluxDB configuration detected
INFO:root:No PVOutput configuration detected
WARNING:root:Modbus connection failed
WARNING:root:Failed to scrape inverter, sleeping until next scan
ERROR:pymodbus.factory:Unable to decode response Modbus Error: Unknown response 0
ERROR:pymodbus.transaction:Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 165, in processIncomingPacket
    self._process(callback, error=True)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request`

anyway..

I can read the logs from inside Portainer interface which is working great!

`INFO:root:{'daily_power_yield': 2900.0, 'total_power_yield': 447.73, 'internal_temp': 41.9, 'pv1_voltage': 301.1, 'pv1_current': 3.7, 'pv2_voltage': 305.9, 'pv2_current': 3.7, 'total_pv_power': 2262, 'grid_voltage': 244.8, 'inverter_current': 9.5, 'total_active_power': 2262, 'grid_frequency': 50.0, 'export_power': -325, 'export_power_indicator': 65535, 'power_meter': 1936, 'daily_purchased_energy': 9.1, 'daily_energy_consumption': 2600.0, 'total_energy_consumption': 779.2, 'year': 2024, 'month': 1, 'day': 31, 'hour': 8, 'minute': 48, 'second': 31, 'timestamp': '31/1/2024 8:48:31'}
INFO:root:Published to MQTT
INFO:root:{'daily_power_yield': 2900.0, 'total_power_yield': 447.73, 'internal_temp': 41.8, 'pv1_voltage': 301.2, 'pv1_current': 3.6, 'pv2_voltage': 304.0, 'pv2_current': 3.6, 'total_pv_power': 2216, 'grid_voltage': 244.6, 'inverter_current': 9.3, 'total_active_power': 2216, 'grid_frequency': 50.0, 'export_power': -274, 'export_power_indicator': 65535, 'power_meter': 1941, 'daily_purchased_energy': 9.1, 'daily_energy_consumption': 2600.0, 'total_energy_consumption': 779.2, 'year': 2024, 'month': 1, 'day': 31, 'hour': 8, 'minute': 48, 'second': 38, 'timestamp': '31/1/2024 8:48:38'}
INFO:root:Published to MQTT`

I can also receive the MQTT messages within HA Core MQTT Listen setting:

`{
    "daily_power_yield": 3300,
    "total_power_yield": 447.73,
    "internal_temp": 44,
    "pv1_voltage": 300.9,
    "pv1_current": 4.1,
    "pv2_voltage": 305.4,
    "pv2_current": 4.1,
    "total_pv_power": 2500,
    "grid_voltage": 243.9,
    "inverter_current": 10.4,
    "total_active_power": 2420,
    "grid_frequency": 50,
    "export_power": 825,
    "export_power_indicator": 0,
    "power_meter": 3245,
    "daily_purchased_energy": 9.1,
    "daily_energy_consumption": 2900,
    "total_energy_consumption": 779.5,
    "year": 2024,
    "month": 1,
    "day": 31,
    "hour": 8,
    "minute": 55,
    "second": 41,
    "timestamp": "31/1/2024 8:55:41"
}`

I'm just really stuck on the next part to add this data to HA in a useful way within the energy tab. could anyone shed some light. (reminder I do not have the add-on page as core)

other that that this is fantastic! thanks very much for all your time and effort.

**Comment by EvoSems** [comment]
forgot to mention if I ever restart my rip or docker image I cannot get past this error? and have to recreate my docker image. is there any way to not have to do this and just keep my docker file always installed and running, restarting etc? thanks.

`INFO:root:Loaded config sungrow-sg5kd
INFO:root:Creating SungrowModbusTcpClient
INFO:root:Connecting
INFO:root:Connected
INFO:root:Configured MQTT Client
INFO:root:No Prometheus configuration detected
INFO:root:No InfluxDB configuration detected
INFO:root:No PVOutput configuration detected
WARNING:root:Modbus connection failed
WARNING:root:Failed to scrape inverter, sleeping until next scan
ERROR:pymodbus.factory:Unable to decode response Modbus Error: Unknown response 0
ERROR:pymodbus.transaction:Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 165, in processIncomingPacket
    self._process(callback, error=True)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
WARNING:root:Modbus connection failed
WARNING:root:Failed to scrape inverter, sleeping until next scan
ERROR:pymodbus.factory:Unable to decode response Modbus Error: Unknown response 0
ERROR:pymodbus.transaction:Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 165, in processIncomingPacket
    self._process(callback, error=True)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
WARNING:root:Modbus connection failed
WARNING:root:Failed to scrape inverter, sleeping until next scan
ERROR:pymodbus.factory:Unable to decode response Modbus Error: Unknown response 0
ERROR:pymodbus.transaction:Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 165, in processIncomingPacket
    self._process(callback, error=True)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
WARNING:root:Modbus connection failed
WARNING:root:Failed to scrape inverter, sleeping until next scan
`

**Comment by EvoSems** [comment]
also if I place the requirement txt with my config.yaml would this read that current requirement.txt and use the modified one over the one in the container? I have read downgrading a requirement to 2.4.0 fixes issues. but it was from a few years ago so I don't know if that is fixed.

can't believe it was working and now it won't work at all. nothing has been changed.. all that happened is inverter went to sleep overnight and I managed to connect first thing this morning. but if you ever stop or restart the container it won't connect again. assuming it might tomorrow morning again
