### ISSUE TITLE
Solariot + SMA Inverters xx000TL-20

### ISSUE THREAD

**Issue by Hoerli1337** [meltaxa/solariot#88]
Hello!
I'm trying to get the whole thing up and running with two SMA inverters.
Have the STP 9000TL-20 and 8000TL-20 here.
I have built myself a suitable py file - linked below - but this doesn't seem to work that way.
When I run it, I get the following message:
root@ctSolariot:/opt/solariot# ./solariot.py -v
INFO:root:Loaded config sma-inverter-xx000tl-20
INFO:root:Creating ModbusTcpClient
INFO:root:Connecting
INFO:root:Connected
INFO:root:No MQTT configuration detected
INFO:root:No Prometheus configuration detected
INFO:root:No InfluxDB configuration detected
INFO:root:No PVOutput configuration detected
Traceback (most recent call last):
  File "/opt/solariot/./solariot.py", line 605, in <module>
    success = scrape_inverter()
  File "/opt/solariot/./solariot.py", line 592, in scrape_inverter
    load_sma_register(modmap.sma_registers)
  File "/opt/solariot/./solariot.py", line 447, in load_sma_register
    message = BinaryPayloadDecoder.fromRegisters(
TypeError: fromRegisters() got an unexpected keyword argument 'endian'

From python I have unfortunately not yet so much ahnung. :(

[modbus-sma-inverter-xx000tl-20.zip](https://github.com/meltaxa/solariot/files/9992682/modbus-sma-inverter-xx000tl-20.zip)

**Comment by retfie** [comment]
For SMA:
```
--- a/solariot.py
+++ b/solariot.py
@@ -494,9 +494,10 @@ def load_sma_register(registers):
)
return

-        message = BinaryPayloadDecoder.fromRegisters(
-            received.registers, endian=Endian.Big
-        )
+        try:
+             message = BinaryPayloadDecoder.fromRegisters(received.registers, byteorder=Endian.Big, wordorder=Endian.Big)
+        except Exception as err:
+             logging.error("[ERROR] BinaryPayloadDecoder: %s" % err)

# Provide the correct result depending on the defined datatype
if type == "S32":
@@ -532,6 +533,10 @@ def load_sma_register(registers):
displaydata = interpreted

logging.debug(f"************** {name} = {displaydata}")
+
+        if isinstance(displaydata, bytes):
+            displaydata = displaydata.decode("utf-8", errors='ignore').replace("\x00", "")
+
inverter[name] = displaydata

# Add timestamp
```
